[build]
  command = "composer install && npm ci && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
